package App::Geshtinanna::CLI::Command::config;

use 5.006;
use strict;
use warnings;
use App::Geshtinanna::CLI -command;
use App::Geshtinanna::SetInfo;
use App::Geshtinanna::Suricata;

our $VERSION = '0.0.1';

=head1 NAME

App::Geshtinanna::CLI::Command::config - Print a default Geshtinanna config.

=head1 SYNOPSIS

    geshtinanna config                                  # every shipped flow, defaults
    geshtinanna config --flow-dir /var/log/suricata/eve # point at your EVE logs
    geshtinanna config --zorita-dir /srv/zorita         # point at your Zorita basedir
    geshtinanna config > /usr/local/etc/geshtinanna.toml

Writes a complete TOML config to STDOUT: the C<[zorita]> table plus one
C<[suricata.flows.<set>]> table for every set shipped under the
F<set_info_jsons> share dir. Flows with an implemented extractor are enabled;
the rest are emitted disabled (no extractor yet) so the file documents every
possible flow without spewing warnings when run.

=cut

sub abstract { 'print a default config covering every Suricata flow' }

sub usage_desc { '%c config %o' }

sub opt_spec {
    return (
        [ 'flow-dir=s',   'directory holding the Suricata EVE JSON logs (default: /var/log/suricata/flows/current)' ],
        [ 'zorita-dir=s', 'Zorita basedir for models/data (default: /var/db/zorita/)' ],
        [ 'slug=s',       'Zorita slug the sets live under (default: suricata)' ],
        [ 'type=s',       'default sink type for every enabled flow: batch|online (default: batch)' ],
        [ 'share=s',      'set_info_jsons share dir (default: dist share dir)' ],
    );
}

sub execute {
    my ( $self, $opt, $args ) = @_;

    my $flow_dir   = $opt->{flow_dir}   // '/var/log/suricata/flows/current';
    my $zorita_dir = $opt->{zorita_dir} // '/var/db/zorita/';
    my $slug       = $opt->{slug}       // 'suricata';
    my $type       = $opt->{type}       // 'batch';

    $type eq 'batch' || $type eq 'online'
        or die "--type must be 'batch' or 'online', not '$type'\n";

    $flow_dir =~ s{/+\z}{};   # normalize a trailing slash off the flow dir

    my $share = App::Geshtinanna::SetInfo->share_dir( $opt->{share} );
    my @sets  = App::Geshtinanna::SetInfo->list_sets( $share, $type );
    @sets
        or die "no set prototypes found under $share/$type\n";

    my %implemented =
        map { $_ => 1 } App::Geshtinanna::Suricata->implemented_flows;

    print $self->_render(
        sets        => \@sets,
        implemented => \%implemented,
        flow_dir    => $flow_dir,
        zorita_dir  => $zorita_dir,
        slug        => $slug,
        type        => $type,
    );
    return;
}

# Render the whole TOML document as a string.
sub _render {
    my ( $self, %a ) = @_;

    my @out = (
        "# Geshtinanna main configuration (generated by `geshtinanna config`).",
        "#",
        "# Installed location: /usr/local/etc/geshtinanna.toml",
        "# (override with the GESHTINANNA_CONFIG env var, or `geshtinanna --config PATH`).",
        "",
        "# Where Zorita keeps its data / online sockets / rendered models.",
        "[zorita]",
        qq{basedir = "$a{zorita_dir}"},
        "",
        "# --- Suricata ingester -------------------------------------------------------",
        "#",
        "# Each [suricata.flows.<set>] table is one Zorita set, matching",
        "# share/set_info_jsons/{online,batch}/Geshtinanna_Suricata_<set>.json.",
        "#",
        "#   enable = true|false        whether to tail this flow      (default: true)",
        "#   type   = \"batch\"|\"online\"  how its model is trained       (default: \"batch\")",
        "#   path   = \"...\"             the EVE log to FollowTail       (required)",
        "[suricata]",
        qq{slug = "$a{slug}"},
        "",
    );

    for my $set ( @{ $a{sets} } ) {
        my $enabled = $a{implemented}{$set} ? 'true' : 'false';
        push @out, "[suricata.flows.$set]";
        push @out, sprintf 'enable = %s', $enabled;
        push @out, sprintf 'type   = "%s"', $a{type};
        push @out, sprintf 'path   = "%s/%s.json"', $a{flow_dir}, $set;
        push @out, '# no extractor implemented yet; events are skipped until one exists'
            unless $a{implemented}{$set};
        push @out, "";
    }

    return join( "\n", @out ) . "\n";
}

=head1 AUTHOR

Zane C. Bowers-Hadley, C<< <vvelox at vvelox.net> >>

=head1 LICENSE AND COPYRIGHT

This software is Copyright (c) 2026 by Zane C. Bowers-Hadley.

This program is released under the following license:

  agpl

=cut

1;
